image: python:3.11

pipelines:
  default:
    - step:
        name: Run tests on push
        script:
          - python -m venv venv
          - source venv/bin/activate
          - if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          - playwright install
          # - pytest tests/
          - pytest -v tests/* --junitxml=test-reports/report.xml

  schedules:
    - cron: "0 */2 * * *"   # Every 2 hours (UTC)
      enabled: true
      branch: main
      step:
        name: Scheduled Test Run
        script:
          - python -m venv venv
          - source venv/bin/activate
          - if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          - playwright install
          # - pytest tests/
          - pytest -v tests/* --junitxml=test-reports/report.xml