
#  Template python-build

#  This template allows you to validate your python code.
#  The workflow allows running tests and code linting on the default branch.

options:
  size: 2x

# image: python:3.11
image: mcr.microsoft.com/playwright/python:v1.44.0-jammy

pipelines:
  default:
    - step:
        name: Run tests on push
        caches:
          - pip
        script:
          # - python -m venv venv
          - python -m pip install --upgrade pip
          # - source venv/bin/activate
          - if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          - playwright install-deps
          - playwright install
          # - pytest tests/
          - pytest -v tests/test_form_present_individual_page.py --junitxml=test-reports/report.xml

