version: 2.1

orbs:
  python: circleci/python@2.0.3 # Use the Python orb for common Python tasks

jobs:
  build-and-test:
    docker:
      - image: mcr.microsoft.com/playwright:v1.40.0-jammy # Use a Playwright-specific Docker image
    steps:
      - checkout # Checkout your code from version control
      - run:
          name: Install Python Dependencies
          command: |
            pip install -r requirements.txt # Install your project's Python dependencies
      - run:
          name: Install Playwright Browsers
          command: |
            playwright install --with-deps # Install Playwright browsers and their dependencies
      - run:
          name: Run Playwright Tests
          command: |
            pytest tests/test_search.py # Or your preferred test runner, e.g., `python your_test_script.py`
      - store_test_results:
          path: test-results/ # Store test results for CircleCI's reporting
      - store_artifacts:
          path: playwright-report/ # Store Playwright reports as artifacts

workflows:
  version: 2.1
  build-and-test-workflow:
    jobs:
      - build-and-test