name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  test:
    timeout-minutes: 180
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Install Playwright Browsers
      run: |
        python -m playwright install
    #- uses: microsoft/playwright-github-action@v1
    - name: Remove existing Playwright cache
      run: rm -rf ~/.cache/ms-playwright
    - name: Install Playwright Browsers
      run: playwright install --with-deps
    - name: Verify Playwright browser files
      run: ls -R ~/.cache/ms-playwright || echo "No browsers found"
    - name: Run Playwright tests
      run: |
        pytest tests/test_search.py
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
