name: Scheduled Playwright Tests

on:
  schedule:
    - cron: '* */6 * * *'  # Run every 6 hours (UTC)
  workflow_dispatch:        # Enables manual trigger from GitHub UI

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Playwright Browsers
        run: |
          python -m playwright install

      - name: Install Playwright Browsers
        run: playwright install --with-deps # previously it was npx playwright install

      - name: Run Playwright tests
        run: |
          pytest tests/